# Generated by Django 4.1.5 on 2023-01-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowersapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(db_index=True, max_length=200, verbose_name='Название магазина')),
                ('store_photo', models.ImageField(db_index=True, upload_to='images', verbose_name='Фото магазина')),
                ('address', models.TextField(db_index=True, verbose_name='Адрес Магазина')),
                ('is_working', models.BooleanField(db_index=True, verbose_name='Работает ли магазин')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phonenumber',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Номер телефона владельца'),
        ),
    ]
