# Generated by Django 4.1.5 on 2023-01-18 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowersapp', '0003_bouquet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_consultation', models.BooleanField(verbose_name='Нужна ли консультация')),
                ('comment', models.TextField(verbose_name='Комментарий к заказу')),
                ('delivery_time', models.DateTimeField(verbose_name='Дата и время заказа')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouquets', to='flowersapp.bouquet', verbose_name='Букет')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='flowersapp.buyer', verbose_name='Покупатель')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='flowersapp.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
