# Generated by Django 4.1.5 on 2023-01-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowersapp', '0005_consultation_alter_bouquet_bouquet_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('сard_number', models.CharField(db_index=True, max_length=200, verbose_name='Номер карты')),
                ('card_date', models.DateField(db_index=True, verbose_name='Срок годности карты')),
                ('owner_name', models.CharField(db_index=True, max_length=200, verbose_name='Имя и фамилия владельца')),
                ('cvv', models.IntegerField(db_index=True, verbose_name='CVV карты')),
            ],
            options={
                'verbose_name': 'Средтсво оплаты',
                'verbose_name_plural': 'Средтсва оплаты',
            },
        ),
    ]
