# Generated by Django 4.1.5 on 2023-01-18 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowersapp', '0006_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='flowersapp.payment', verbose_name='Оплата'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='сonsultation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='сonsultations', to='flowersapp.consultation', verbose_name='консультация'),
        ),
    ]
