# Generated by Django 4.1.5 on 2023-01-18 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowersapp', '0007_buyer_payment_buyer_сonsultation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_consultation',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_payments', to='flowersapp.payment', verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='address',
            field=models.TextField(db_index=True, verbose_name='Адрес покупателя'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_payments', to='flowersapp.payment', verbose_name='Оплата'),
        ),
    ]
