# Generated by Django 4.1.5 on 2023-01-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowersapp', '0008_remove_order_is_consultation_order_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='composition',
            field=models.TextField(blank=True, db_index=True, verbose_name='Композиция букета'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='description',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание букета'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='size',
            field=models.TextField(blank=True, db_index=True, verbose_name='Размер букета'),
        ),
    ]
