# Generated by Django 4.1.5 on 2023-01-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowersapp', '0009_bouquet_composition_bouquet_description_bouquet_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bouquet',
            name='amount',
        ),
    ]
