# Generated by Django 4.1.5 on 2023-01-18 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowersapp', '0010_remove_bouquet_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='bouquet_photo',
            field=models.ImageField(db_index=True, upload_to='images', verbose_name='Фото букета'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='address',
            field=models.TextField(blank=True, db_index=True, verbose_name='Адрес покупателя'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='Почта покупателя'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='сonsultation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='flowersapp.consultation', verbose_name='консультация'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='phonenumber',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Номер телефона покупателя'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='store_photo',
            field=models.ImageField(db_index=True, upload_to='images', verbose_name='Фото магазина'),
        ),
    ]
