# Generated by Django 4.1.5 on 2023-01-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowersapp', '0011_alter_bouquet_bouquet_photo_alter_buyer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='recommend',
            field=models.BooleanField(default=False, verbose_name='Рекомендуем'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='slug',
            field=models.SlugField(max_length=200, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='bouquet_photo',
            field=models.ImageField(db_index=True, upload_to='', verbose_name='Фото букета'),
        ),
    ]
