# Generated by Django 4.1.5 on 2023-01-19 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowersapp', '0012_bouquet_recommend_bouquet_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bouquet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bouquets', to='flowersapp.bouquet', verbose_name='Букет'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='flowersapp.buyer', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Дата и время заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='flowersapp.shop', verbose_name='Магазин'),
        ),
    ]
