# Generated by Django 4.1.5 on 2023-01-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowersapp', '0015_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, db_index=True, verbose_name='Адрес доставки'),
        ),
    ]
