# Generated by Django 4.1.5 on 2023-01-19 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flowersapp", "0016_order_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="BouquetQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer_event",
                    models.CharField(
                        max_length=255, null=True, verbose_name="ответ событие"
                    ),
                ),
                (
                    "answer_price",
                    models.CharField(
                        max_length=255, null=True, verbose_name="ответ стоимость"
                    ),
                ),
                (
                    "bouquet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bouquet",
                        to="flowersapp.bouquet",
                        verbose_name="букет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подобранный букет",
                "verbose_name_plural": "Подобранные букеты",
            },
        ),
    ]
