# Generated by Django 4.1.5 on 2023-01-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flowersapp", "0015_merge_0014_bouquet_recommend_0014_order_is_active"),
        ("flowersapp", "0016_order_address"),
    ]

    operations = []
