# Generated by Django 4.1.5 on 2023-01-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowersapp', '0017_bouquetquiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='store_photo',
            field=models.ImageField(db_index=True, null=True, upload_to='images', verbose_name='Фото магазина'),
        ),
    ]
