# Generated by Django 4.1.5 on 2023-01-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowersapp', '0018_alter_shop_store_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='store_photo',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to='images', verbose_name='Фото магазина'),
        ),
    ]
