# Generated by Django 4.1.5 on 2023-01-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowersapp', '0020_remove_payment_card_date_payment_month_payment_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='lat',
            field=models.FloatField(default=92.852572, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='shop',
            name='lng',
            field=models.FloatField(default=56.010569, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='shop',
            name='phonenumber',
            field=models.CharField(db_index=True, default='+79999999999', max_length=20, verbose_name='Номер телефона магазина'),
        ),
    ]
